version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dbicd10
      - POSTGRES_USER=ebo
      - POSTGRES_PASSWORD=1pmn3t1vPG
      - DATABASE_URL:"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db:5432/{POSTGRES_DB}"

  migration:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - migration
